# Generated by Django 3.0 on 2019-12-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('image', models.ImageField(default='images/None/no-img.jpg', upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftlistapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(blank=True, max_length=100)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftlistapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftlistapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Jewelery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrainfo', models.CharField(blank=True, max_length=100)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftlistapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=3)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftlistapp.Product')),
            ],
        ),
    ]
