# Generated by Django 3.0 on 2019-12-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftlistapp', '0002_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
