# Generated by Django 2.1.5 on 2019-12-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftlistapp', '0004_auto_20191219_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
